### ISSUE TITLE
V1 TODO

### ISSUE THREAD

**Issue by pricklypointer** [pricklypointer/JuliaPkgStats#1]
- [ ] Add custom date ranges on Top/All/Pkg stats
- [ ] Add dropdown to modify OS/Arch graph on `All` to choose between Arch/OS/All
- [ ] Package comparison page
- [ ] Integrate additional package stats such as commit count, github stars, and other stats from PackageAnalyzer.jl.
- [ ] Add section for trending packages on increases in download count, contributors, stars,...
- [ ] Add `/pkg` page and `/pkg/:package_name` page for suggested search results when the search isn't a valid package
- [ ] Make the `enter` key create the badge code on `/API`, similar to the search bar.
- [ ] Fix how the website looks on mobile
